### ISSUE TITLE
may you share link to paper Ranking Influencers on Social Collaboration Platforms

### ISSUE THREAD

**Issue by Sandy4321** [DerekChiangTW/social_influencer#1]
may you share link to paper Ranking Influencers on Social Collaboration Platforms

**Comment by DerekChiangTW** [comment]
I uploaded the paper.

**Comment by Sandy4321** [comment]
great thanks 
only references in this pdf file are different than in 
https://ieeexplore.ieee.org/abstract/document/8356897/
1.  
Daniel Gruhl, R. Guha, David Liben-Nowell, Andrew Tomkins, "Information diffusion through blogspace", Proc. WWW, pp. 491-501, 2004.
 Show Context Access at ACM 
2.  
Meeyoung Cha, Alan Mislove, Krishna P. Gummadi, "A measurement-driven analysis of information propagation in the flickr social network", Proc. WWW, pp. 721-730, 2009.
 Show Context Access at ACM 
3.  
Liangjie Hong, Ovidiu Dan, Brian D. Davison, "Predicting popular messages in twitter", Proc. WWW, pp. 57-58, 2011.
 Show Context Access at ACM 
4.  
Lu Liu, Jie Tang, Jiawei Han, Shiqiang Yang, "Learning influence from heterogeneous social networks", Data Min. Knowl. Discov., vol. 25, no. 3, pp. 511-544, 2012.
 Show Context CrossRef  Google Scholar 
5.  
Antonio Lima, Luca Rossi, Mirco Musolesi, "Coding together at scale: Github as a collaborative social network", Proc. AAAI ICWSM, pp. 295-304, 2014.
 Show Context
6.  
Peter Mutschke, "Mining Networks and Central Entities in Digital Libraries" in A Graph Theoretic Approach Applied to Co-author Networks, Berlin Heidelberg:Springer, pp. 155-166, 2003.
 Show Context
7.  
Scott White, Padhraic Smyth, "Algorithms for estimating relative importance in networks", Proc. ACM SIGKDD, pp. 266-275, 2003.
 Show Context Access at ACM 
8.  
Yin Li-chun, Hildrun Kretschmer, Robert A. Hanneman, Liu Ze-yuan, "Connection and stratification in research collaboration: An analysis of the collnet network", Inf. Process. Manage., vol. 42, no. 6, pp. 1599-1613, dec 2006.
 Show Context
9.  
Xiaoming Liu, Johan Bollen, Michael L. Nelson, Herbert Van de Sompel, "Co-authorship networks in the digital library research community", Inf. Process. Manage., vol. 41, no. 6, pp. 1462-1480, dec 2005.
 Show Context CrossRef  Google Scholar 
10.  
Erjia Yan, Ying Ding, "Discovering author impact: A pagerank perspective", Inf. Process. Manage., vol. 47, no. 1, pp. 125-134, jan 2011.
 Show Context CrossRef  Google Scholar 
11.  
Na Li, Denis Gillet, "Identifying influential scholars in academic social media platforms", Proc. ACM ASONAM, pp. 608-614, 2013.
 Show Context View Article Full Text: PDF	(319KB)
12.  
Steffen Rendle, "Factorization machines", Proc. IEEE ICDM, pp. 995-1000, 2010.
 Show Context View Article Full Text: PDF	(277KB)
13.  
Steffen Rendle, "Factorization machines with libfm", ACM Trans. Intell. Syst. Technol., vol. 3, no. 3, pp. 57: 1-57: 22, May 2012.
 Show Context Access at ACM 
14.  
Sergey Brin, Lawrence Page, "The anatomy of a large-scale hyper-textual web search engine", Proc. WWW, pp. 107-117, 1998.
 Show Context
