### ISSUE TITLE
May you help understand where is approach based on factorization machines (FM).

### ISSUE THREAD

**Issue by Sandy4321** [DerekChiangTW/social_influencer#2]
May you help understand where is approach based on factorization machines (FM)?

**Comment by DerekChiangTW** [comment]
We want to learn the indirect influence between user-item pair.
Based on the direct influence in the user-item matrix, we can learn indirect influence using FM.

For example, if A (a person) collaborate with B (a person) to write a paper about Machine Learning.
Based on their collaboration, there exists some direct connection between A and B on ML. If person A wrote another paper about ML 1 year later, we assume that B will have certain degree of indirect influence on this paper too, based on their previous collaboration. We build the user-item matrix and learn these indirect influence using FM.

**Comment by Sandy4321** [comment]
sounds great
only may you help understand where it is in code
what lines execute this FM
